version: "3.7"
networks:
  warehouse_network:
services:
  warehouse-db-postgres:
    container_name: warehouse_db_postgres
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - warehouse_network